matrix:
  include:
  - language: python
    python:
      - "3.7-dev"
    branches:
      only:
        - master
    before_install:
      - cd backend
    install:
      - pip install -r requirements.txt
    script:
      - pytest

  - language: node_js
    node_js:
      - "8"
    branches:
      only:
        - master
    cache:
      directories:
        - frontend/node_modules
    before_install:
      - cd frontend
    install:
      - npm install
    script:
      - npm run test

